language: node_js
script: npm test
node_js:
  - "9.3"

after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success:
  - npm run dist:release

addons:
  artifacts:
    paths:
      - $(ls ./dist/*.js | tr "\n" ":")
      - $(ls ./examples/* | tr "\n" ":")
      - $(ls ./themes/* | tr "\n" ":")
    target_paths:
      - webshell.js
